### ISSUE TITLE
Need description of netconfig json files.

### ISSUE THREAD

**Issue by fmaxwell** [uboslinux/ubos-docs#30]
While I'm fine editing a .json file with nano, it would be very useful to have a description of the parameters in the netconfig json files.  For example "forwarding."  Port forwarding?  DNS request forwarding?  What happens if an IP address is there and DHCP is set to true?  Which one "wins"?  How does one designate which port is WAN and which is LAN in setups with both?  How does one disable a port?  How does one specify gateway and DNS server IP addresses?

**Comment by jernst** [comment]
You shouldn't really have to edit those files except under very peculiar circumstances. What are you trying to accomplish? Perhaps it would better be a new kind of netconfig.

**Comment by fmaxwell** [comment]
I have two network segments, each with its own gateway:

192.168.0.1		pfSense router/firewall on business Internet connection for servers
192.168.1.1		Linksys WiFi router/firewall on residential Internet for general Internet access

The two segments are bridged together via a switch and the systems use a netmask of 255.255.254.1 so that all local systems can see one another.  

But I can’t have the router/firewall on each segment racing to supply DHCP lease requests that come through the switch.   So I only have the 192.168.1.1 router/firewall answering DHCP requests.  

But it can’t provide anything other than it’s own LAN IP as the gateway for a DHCP lease.  That means that the servers on the 192.168.0.1 business networks need static IP addresses.  I absolutely don’t want any other device answering DHCP lease requests.

The system I'm connecting has a WiFi adapter, which I want to turn off, and a gigabit Ethernet port which I want to use as the NIC.

**Comment by jernst** [comment]
This is definitely not a very common configuration among home users :-)
The device you are connecting is supposed to be just "client" on that network, correct, not a router/dhcp server etc?
If you just say `ubos-admin setnetconfig client`, how is that different from the configuration you want? Or is the device supposed to go to the static-IP net?

**Comment by fmaxwell** [comment]
I'll be careful with the terminology here.  The UBOS device will be an ownCloud _server with a static IP_ on the business segment (192.168.0.0/24) of the network. It will _not_ be a DHCP server or client.  It will _not_ act as a router, gateway, for firewall for other systems on the network.  

It will have its own static IP address on the Internet (through NAT port forwarding at the pfSense router/firewall) and will have DNS records that point to it, allowing remote access (outside of my home).  Over time, I may add other web apps like Wordpress to it.  

There is a logic behind my configuration, which I'll share in a private email rather than over-complicating this ticket.

**Comment by jernst** [comment]
There isn't currently a netconfig type that does this out of the box. The best avenue would be to create a new one (say netconfig ``static``), which would be similar to ``standalone`` but not run DHCP etc. The best way to do that would be to copy https://github.com/uboslinux/ubos-admin/tree/master/ubos-networking-standalone, update the names, and then change the settings in the ``activate`` method according to your needs. Happy to accept a pull request.

There are some additional example settings here: https://github.com/uboslinux/ubos-admin/blob/master/ubos-networking/example.json (although I'm not certain this file is up-to-date) and you can also look at the ``activate`` methods of the other ``netconfig`` typpes. If you are still unclear about which setting does what, the best way to proceed would be for you to document the settings as well as you can in some suitable place in the UBOS documentation, and I'll review and complete.

**Comment by jernst** [comment]
And here it is: http://ubos.net/docs/developers/networking.html
