### ISSUE TITLE
Add sub-chapter in chapter The UBOS staff: "After generating/updating UBOS staff keys"

### ISSUE THREAD

**Issue by Tiger862000** [uboslinux/ubos-docs#37]
Following information is missing:
After UBOS keys were generated do the following 
`shutdown -h now`
Unplug USB / UBOS-Staff and insert it into PC you want to remotely connect to your UBOS device. Then move private key to /home/user/.ssh/ by typing
`mv path-to-UBOS-STAFF-private-key home/user/.ssh/authorized_keys`
Make key safe by changing its user rights to
`chmod 644 /home/user/.ssh/authorized_keys`

**Comment by jernst** [comment]
Note: shutdown is actually not required: UBOS automatically unmounts the staff device once it is done with it.
