### ISSUE TITLE
UBOS-Staff: key at remote machine

### ISSUE THREAD

**Issue by Tiger862000** [uboslinux/ubos-docs#38]
I was missing the explanation on what to do after UBOS-Staff was generated and is actually ready for usage on remote machine.
The documentation could continue somewhere around here: ...unplug USB / UBOS-Staff...
1.) copy key to /home/user/.ssh/
2.) make key safe with changeing user rights to 
 `chmod 644 /home/user/.ssh/authorized_keys`

then you could add a link to 

>  Connect via SSH to your server from your PC

**Comment by jernst** [comment]
Would you like to make the change and submit a pull request? :-)
