### ISSUE TITLE
Responses from is-system-running

### ISSUE THREAD

**Issue by julianfoad** [uboslinux/ubos-docs#46]
http://ubos.net/docs/users/installation/virtualbox.html says

> 8. Wait until UBOS is ready. You can tell by executing:
> > systemctl is-system-running

Needs to say here what response we are expecting. I saw the response "degraded" and it wasn't clear what this meant ... is it running, or not running yet, or is this an exceptional (unexpected) state? For a long time at first, I assumed it meant not running, and so I kept on waiting for hours.

It just needs to say something like (but I don't know if this is exactly right):

"When the response is 'yes' you can proceed; if the response is 'no' you need to wait longer; any other response may mean something has gone wrong."

(To be clear: this ticket is not a request for support for my system's 'degraded' state; I'll do that separately in the appropriate support channels.)

**Comment by jernst** [comment]
If this text is updated, the equivalent text must also be updated for other platforms.

**Comment by jernst** [comment]
@julianfoad How is this?

**Comment by julianfoad** [comment]
That looks lovely. Thanks.

(Nit-pick: in one place, in sphinx/users/installation/armv6h_container.rst in "consult the troubleshooting page" you deleted only "the" and not "page".)
