### ISSUE TITLE
Default mDNS hostnames

### ISSUE THREAD

**Issue by julianfoad** [uboslinux/ubos-docs#47]
http://ubos.net/docs/users/networking.html#mdns-hostnames

For a Virtual PC in VirtualBox, it says
    ubos-vbox-pc.local
But in fact it comes up with a hostname of
    ubos-vbox-x86_64
and the mDNS name is
    ubos-vbox-x8664.local

... note the missing underscore.

This is the recent (November) UBOS yellow release, in VirtualBox on Ubuntu 16.04 x86_64.

The doc should correct and clarify this, and say how to check the exact name (perhaps with the help of an 'avahi-browse' command?).

**Comment by jernst** [comment]
The documentation is correct, this should be fixed in the code. Moved there.
