### ISSUE TITLE
Verify downloads

### ISSUE THREAD

**Issue by pyj677** [uboslinux/ubos-docs#49]
I'm just starting with UBOS by downloading an img.xz file.

I also downloaded the corresponding img.xz.sig file but wasted quite some time finding the key needed to do the download verification.  ( I finally found it in uboslinux/ubos-admin/ubos-keyring/ubos.gpg )

Luckily, I knew how to import it and rerun the verify - but why not just document it?

(If the correct way to do this is documented somewhere, I failed to find it!)

**Comment by jernst** [comment]
Makes sense to document this. Pull requests appreciated :-)

**Comment by jernst** [comment]
See https://github.com/uboslinux/ubos-docs/pull/50
