### ISSUE TITLE
nextcloud11 file size permissions blocked

### ISSUE THREAD

**Issue by rp25** [uboslinux/ubos-docs#52]
installed using: ubos-admin createsite
...
app: nextcloud11
...

Once in nextcloud11 admin console. The file upload size limit is grayed out. "Missing permissions to edit from here."

**Comment by jernst** [comment]
This would modify one of the Nextcloud config files, and I'm not a great fan of web apps doing that themselves for security reasons. So that's why this is grayed out.

If you want to change the parameter, you can, as root, edit `/etc/php/php.init` and change the parameter there. If you do, make sure you restart the web server: `sudo systemctl restart ubos-httpd`

**Comment by rp25** [comment]
This works for files uploaded to the user's account. The limit is still in place for external storage. Uploading a large to file to S3 throws an error. 

> {"reqId":"byY/fitVgV3ufjkitJey","remoteAddr":"134.192.250.6","app":"PHP","message":"is_writeable(): open_basedir restriction in effect. File(/var/big_temp_file) is not within the allowed path(s): (/srv/http/sites/sd9bf431aff52b1339ace242a22b3f932532fce6e:/tmp/:/usr/share/:/dev:/var/lib/nextcloud11/aba4bd974365a0e57a33d324b1c18ec6b120afda7) at /srv/http/sites/sd9bf431aff52b1339ace242a22b3f932532fce6e/lib/private/TempManager.php#259","level":3,"time":"2017-04-14T17:33:35+00:00","method":"GET","url":"/","user":"--","version":"11.0.0.10"}

**Comment by jernst** [comment]
Could you describe, step by step, what you did to until this error occurred. E.g. how did /var/big_temp_file get there?

**Comment by rp25** [comment]
Following the documentation on nextcloud.com, I increased  upload_max_filesize, post_max_size , max_input_time , and max_execution_time in  /etc/php/php.init. I created  /var/big_temp_file/
and set upload_tmp_dir to it. Both /var and /var/big_temp_file/ have read and write permissions. I restarted the server. I added an external storage through nextcloud (AWS S3).  Attempting to upload a file > 512 MB to the external storage fails.

**Comment by jernst** [comment]
I see. The "problem" is that you picked an arbitrary location in the filesystem where to put your large files, and for security reasons, Nextcloud on UBOS is not permitted to access arbitrary locations in the filesystem. The error message does tell you where the allowed locations are.

**Comment by rp25** [comment]
Thank you. Where do you recommend I create a temporary directory in the allowed locations?
