### ISSUE TITLE
Add more documentation about the router and firewall functionality on espressobin?

### ISSUE THREAD

**Issue by klundry** [uboslinux/ubos-docs#64]
`New features:

    The EspressoBIN can now be used as a router with firewall, and is in fact pre-configured that way. It runs a firewall, IP address translation, a DHCP and a local DNS server.`

In order to use ubos on the espressobin as a router, how are users expected to manage the firewall, dhcp leases and dns entries?  Say I want to forward some ports to a server on my lan? Or manually set an internal dns entry for a server on my lan? Or set static ips for certain servers?

**Comment by jernst** [comment]
Manual port forwarding isn't currently supported out of the box, but the others are: you can add to the `dnsmasq` configuration by adding files info `/etc/dnsmasq.d`. E.g. for my home router, I have a Mac-address-based white list with static IP addresses there. See `dnsmasq` documentation.

Would be worthwhile to write some documentation about that ...

**Comment by klundry** [comment]
Is manual port forwarding planned? Is the firewall just using iptables?

dnsmasq looks like it can do everything else, thanks.  Are you using the espressobin as your router now? How is the performance?

**Comment by jernst** [comment]
I'm worried about the usability of port forwarding ... e.g. all of a sudden we need to worry about port conflicts. Would be nice if it was an (extremely simple) "app" that fit into the overall paradigm.

I'm using a dual-Ethernet PC as my router. Not sure when/if I will move to EspressoBIN.

**Comment by klundry** [comment]
Ah, yeah I see how that could cause some unexpected behavior for inexperienced users. 

What about ssh? Is there not a way to allow ssh connections on non-standard ports?

**Comment by jernst** [comment]
Why would you want to do that?

**Comment by klundry** [comment]
Because port 22 is always scanned like crazy. I usually pick a random high number port that isn't used for anything.

**Comment by jernst** [comment]
I see. I which case, edit your ssh config so it uses the port you want, and add that port into a new file in /etc/ubos/open-ports.d using the same format as what's there already. Then `ubos-admin setnetconfig` and the firewall will let traffic pass on that port.
