### ISSUE TITLE
Request: Documentation focus on using external drive with raspberry pi

### ISSUE THREAD

**Issue by Jan-Jan** [uboslinux/ubos-docs#65]
1st, thank you very much for `ubos` it is a great project.

When burning `ubos_yellow_armv7h-rpi2_20171103-190406.img.xz` to SD card, I encountererd that my card was not fully used, instead the partition created was tiny. This and running on the SD card caused nextcloud to run very slow. 

Instead I redid everything so that ubos could boot from an external drive instead. I think this will be the use case for the majority of raspberry pi users, since we are building data servers here. I suggest / request that the documentation process be optimised and updated for this approach instead.

**Comment by jernst** [comment]
It woud be good to know what exactly you did "so that ubos could boot from an external drive instead". Are you saying without an SD card at all, on the Raspberry Pi 3? (I think it only works on the 3, not on the other Pis but could be wrong -- I have not tried myself)

**Comment by Jan-Jan** [comment]
I used the `/boot` partition from the raspberry pi 3, and the `/dev/sda1/` from my external as root, ie, `/`.

**Comment by Jan-Jan** [comment]
What I had to do was dd as per the ubos instructions, 
then rsync root `/` from the sdcard to my external,
then update `/boot/cmdline.txt` to point to `/dev/sda1`
then update `/etc/fstab` (on `/dev/sda1`) to mount itself as root

**Comment by jernst** [comment]
Ah, I see. That probably works, but I'm not certain how well `rsync` deals with "special" files. Alternatively you should be able to boot from SD card, and run `ubos-install /dev/sda`.

Added to the documentation: https://github.com/uboslinux/ubos-docs/commit/87a353844097a9aba5bd6c33d40d2a253f266f54 . Does this make sense to you?

**Comment by Jan-Jan** [comment]
That looks awesome. It is nice, simple, easy to follow.
Keep up the great work.

**Comment by jernst** [comment]
See https://ubos.net/docs/users/devices/raspberrypi.html
