### ISSUE TITLE
Explain how to use SSH on Windows (public-/private-keys) with putty

### ISSUE THREAD

**Issue by FruechteKoenig** [uboslinux/ubos-docs#69]
Hello,
I just figured out how to use the generated private-key to authenticate on my raspberry pi with ubos via ssh.
Sadly it isn't documented in the Documentation section under "The UBOS Staff". (https://ubos.net/docs/users/shepherd-staff.html) There I just found an explanation for Linux/Mac users.
Windows users have to generate an extra private-key via the putty-gen-tool, which they can use in the putty-client for authentication.
Could you add a section/hint/sentence for that?

Thanks.

**Comment by jernst** [comment]
Could you write such a section/hint/sentence, and add here in the comments, or submit a pull request? That would be most helpful ...

**Comment by jernst** [comment]
Thank you! I'll add it.
