### ISSUE TITLE
Need documentation about how to use rsync+ssh

### ISSUE THREAD

**Issue by Hubfornature** [uboslinux/ubos-docs#88]
Followed by the UBOS document of [https://ubos.net/docs/users/backup.html](https://ubos.net/docs/users/backup.html)
it may need more examples for the remote backups, especially for rsync+ssh.

So please take this into your account when you are going to make new updates on the current docs.

**Comment by jernst** [comment]
What is the specific question that the documentation does not answer?

**Comment by Hubfornature** [comment]
Hi there, please see below UBOS forum article regarding this issue.

https://forum.ubos.net/viewtopic.php?f=14&t=1691

**Comment by Hubfornature** [comment]
> 
> 
> What is the specific question that the documentation does not answer?

Hi there, please see below UBOS forum article regarding this issue.

https://forum.ubos.net/viewtopic.php?f=14&t=1691
